apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: conversao-temperatura
        image: k8syns/guia-jenkins:{{tag}}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP

